### ISSUE TITLE
eTax TODO List

### ISSUE THREAD

**Issue by kittiu** [ecosoft-odoo/kanban#160]
- [ ] Print Tax Invoice / Receipt from JE @ps-tubtim  https://github.com/ecosoft-odoo/kanban/issues/152
- [ ] Study how to generate PDF/A3 @Saran440 
  - https://github.com/OCA/edi/tree/10.0/account_invoice_factur-x
  - https://www.getinvoice.net/%E0%B8%A3%E0%B8%B9%E0%B9%89%E0%B8%88%E0%B8%B1%E0%B8%81-pdf-a-3-%E0%B8%97%E0%B8%B5%E0%B9%88%E0%B9%83%E0%B8%8A%E0%B9%89%E0%B8%97%E0%B8%B3-e-tax-invoice-%E0%B8%81%E0%B8%B1%E0%B8%99/
- [ ] A web service method that will print form PDF as ir.attachment and send back the URL
