### ISSUE TITLE
ACM Issues

### ISSUE THREAD

**Issue by newtratip** [ecosoft-odoo/kanban#42]
### TODO
- [x] Breach Agreement #28 @newtratip 
- [x] Terminate Agreement #33 @newtratip 
- [x] Extension Agreement #32 @newtratip 
- [x] Transfer Agreement #31 @newtratip 
- [x] Goods Category #27 @newtratip 
- [x] Move fields in product page #35 @newtratip 
- [x] Adjust column to display on agreement (List view) #34 @newtratip 
- [x] Batch Invoice #36 @kongrattapong 
- [x] Rental Collect Form #38 @kongrattapong
- [ ] Automate Agreement name but allow editing / override #29 @newtratip  
- [ ] Script to update structure on agreement (recitals, sections, clauses, appendices) #43 @newtratip 
- [ ] Should have better logging in chatter
- [ ] k.Ping need Sales Order or จดหมายการเสนอขายใหม่ (สำหรับการต่อสัญญาด้วย) อยากให้การ log การเจรจาว่าเคยเสนอไปที่เท่าไร ก่อนที่จะ final
- [ ] การออก invoice ต้องการให้ออกเป็น auto เมื่อได้เงินแล้วจึงมากดจ่ายเงิน
- [ ] มีปัญหาว่าการที่ต้องเลือกว่า 4 สินค้าต้องมาเลือกแต่ละครั้งคงไม่สะดวก แต่น่าจะต้องสามารถเซตได้ตั้งแต่ที่ Agreement
- [ ] การโอนสิทธิ์จะต้องมีการคำนวณใหม่โดยมีสูตร...สามารถทำ auto ได้ไม๊
- [ ] การต่อสัญญา ต้องการให้มีการเพิ่มเงินได้เป็น % ในกรณีที่มีการต่อสัญญา เช่นกัน อาจต้องมี logic ในการเพิ่ม config อยู่ใน Agreement
- [ ] การ terminate เรื่องการคืนเงินยังไม่ได้ทำ (ณ ตอนนี้ทำตรงที่หน้า journal entry)
- [ ] หมดสัญญา ควรจะ auto ด้วยเงื่อนไขเวลาที่มันหมดลง
- [ ] Format address to fit with Thailand #30

**Comment by newtratip** [comment]
Old issues.
